"""modelado jpastor centro comerical

Revision ID: 346cbbc168a3
Revises: 943e8132eb25
Create Date: 2024-11-27 00:01:42.101526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346cbbc168a3'
down_revision = '943e8132eb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_comerciales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=False),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('imagen_portada', sa.String(length=255), nullable=True),
    sa.Column('imagen1', sa.String(length=255), nullable=True),
    sa.Column('imagen2', sa.String(length=255), nullable=True),
    sa.Column('imagen3', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('centros_comerciales')
    # ### end Alembic commands ###
